# Spring properties
spring:
  application:
      name: account-service
  datasource:
        url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_5ef3f6350244852?reconnect=true
        username: b104e75491ae52
        password: 3732038a
        tomcat:
          max-active: 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: https://superteam-eurekaserver.herokuapp.com/eureka/
  instance:
    instanceId: superteam-accountservice.herokuapp.com
    hostname: superteam-accountservice.herokuapp.com
    non-secure-port: 80

# HTTP Server
#server:
#  port: 2224   # HTTP (Tomcat) port

security:
 oauth2:
   resource:
     jwt:
       keyValue: |
         -----BEGIN PUBLIC KEY-----
         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmFvAlmMZTwdUfgR0O4WhyKjp3iGhPhur+qcXMWjFb/I7SesxjzfD0o7g51x1eruk4cGE82V5nQ5DPBqje7uJjY08R6t/W8qVfOWYkFm58ZPcqtKHQeB3MY3FR+0iGkXobfjcVnYPmnSnnT9tjHx5oE+ljd0eXNovNvpa3yisraxGC5mqGsxkO0QiaAMm8nxI/ns7c6bUaQpGyLqbxJRgtt//90GMNVEigxww7LrloQqTaBDJP98YYTjf3i47RPyQobFYGZHWNz3Z2pnBehvLkf6YBuuw6i9CsTtm0+TwuWhgKnenERSmOFvGZc2BXCaILVzeqidBoz4ue8V5BhRhlQIDAQAB
         -----END PUBLIC KEY-----